server:
  port: 8082

spring:
  application:
    name: discovery-service

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
    register-with-eureka: false
    fetch-registry: false

message: ${project.parent.basedir} This message in the git repository v2