spring:
  jpa:
    database: postgresql
    show-sql: true
  #    hibernate:
  #      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/tasks_single_select
    username: mick
    password: mick
    platform: postgres
    driver-class-name: org.postgresql.Driver
  cloud:
    config:
      test:
        message: Это тестовое сообщение для проверки работы Spring Cloud Config Server храниться в /shared в модуле configuration


server:
  port: 0
  servlet:
    context-path: /tasks-chemsingleselect-application/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

kafka:
  server: http://localhost:9092
  groupId: tasks-single-select-service.1